# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import messenger_pb2 as messenger__pb2


class messengerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.send = channel.unary_unary(
        '/ousystems.messenger/send',
        request_serializer=messenger__pb2.Msg.SerializeToString,
        response_deserializer=messenger__pb2.MsgAck.FromString,
        )


class messengerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def send(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_messengerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'send': grpc.unary_unary_rpc_method_handler(
          servicer.send,
          request_deserializer=messenger__pb2.Msg.FromString,
          response_serializer=messenger__pb2.MsgAck.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ousystems.messenger', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
