# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messenger.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messenger.proto',
  package='ousystems',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fmessenger.proto\x12\tousystems\"+\n\x03Msg\x12\x13\n\x0binstruction\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x03(\t\"2\n\x06MsgAck\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0b\n\x03src\x18\x02 \x01(\t\x12\x0b\n\x03\x64st\x18\x03 \x01(\t\"\x19\n\x07NullMsg\x12\x0e\n\x06status\x18\x01 \x01(\x05\x32\x38\n\tmessenger\x12+\n\x04send\x12\x0e.ousystems.Msg\x1a\x11.ousystems.MsgAck\"\x00\x62\x06proto3')
)




_MSG = _descriptor.Descriptor(
  name='Msg',
  full_name='ousystems.Msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instruction', full_name='ousystems.Msg.instruction', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='ousystems.Msg.content', index=1,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=73,
)


_MSGACK = _descriptor.Descriptor(
  name='MsgAck',
  full_name='ousystems.MsgAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ousystems.MsgAck.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='src', full_name='ousystems.MsgAck.src', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dst', full_name='ousystems.MsgAck.dst', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=125,
)


_NULLMSG = _descriptor.Descriptor(
  name='NullMsg',
  full_name='ousystems.NullMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ousystems.NullMsg.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=152,
)

DESCRIPTOR.message_types_by_name['Msg'] = _MSG
DESCRIPTOR.message_types_by_name['MsgAck'] = _MSGACK
DESCRIPTOR.message_types_by_name['NullMsg'] = _NULLMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Msg = _reflection.GeneratedProtocolMessageType('Msg', (_message.Message,), {
  'DESCRIPTOR' : _MSG,
  '__module__' : 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:ousystems.Msg)
  })
_sym_db.RegisterMessage(Msg)

MsgAck = _reflection.GeneratedProtocolMessageType('MsgAck', (_message.Message,), {
  'DESCRIPTOR' : _MSGACK,
  '__module__' : 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:ousystems.MsgAck)
  })
_sym_db.RegisterMessage(MsgAck)

NullMsg = _reflection.GeneratedProtocolMessageType('NullMsg', (_message.Message,), {
  'DESCRIPTOR' : _NULLMSG,
  '__module__' : 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:ousystems.NullMsg)
  })
_sym_db.RegisterMessage(NullMsg)



_MESSENGER = _descriptor.ServiceDescriptor(
  name='messenger',
  full_name='ousystems.messenger',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=154,
  serialized_end=210,
  methods=[
  _descriptor.MethodDescriptor(
    name='send',
    full_name='ousystems.messenger.send',
    index=0,
    containing_service=None,
    input_type=_MSG,
    output_type=_MSGACK,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MESSENGER)

DESCRIPTOR.services_by_name['messenger'] = _MESSENGER

# @@protoc_insertion_point(module_scope)
